load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "divider_test",
    srcs = ["divider_tests.cpp"],
    deps = [
        "//src/division:division",
        "@com_google_googletest//:gtest_main",
    ],
)
