load("@rules_cc//cc:defs.bzl", "cc_binary")
## Replace workspace_name and dir_path as per your setup.
# load("@com_grail_bazel_compdb//:defs.bzl", "compilation_database")
# load("@com_grail_bazel_output_base_util//:defs.bzl", "OUTPUT_BASE")

cc_binary(
    name = "main",
    srcs = ["main.cpp"],
    # hdrs = ["main.h"],
    deps = ["//src/division:division"],
)
